### ISSUE TITLE
Why is Http<OtherExecutor> not supported

### ISSUE THREAD

**Issue by hicqu** [tower-rs/tower-hyper#27]
I'm confused why `Http<DefaultExecutor>` is the only choise in `Server::serve_with`. Is there any special reasons to forbid `Http<tokio_threadpool::Sender>`?

**Comment by LucioFranco** [comment]
hi @hicqu!

Yeah, this is a limitation due to the fact that `hyper` does not expose its `H2Exec` trait and `Exec` enum. [Here](https://github.com/hyperium/hyper/issues/1704) is the related issue. I am going to revert the change that added the `Serve` future to just use a `Box<Future>` for now since this will allow us to erase and punt on the bounds for the executor. This should enable you to use any executor.

Let me know if there is any issue with this.

**Comment by LucioFranco** [comment]
PR is up at #28

**Comment by hicqu** [comment]
Thank you. It can be closed now.

**Comment by hicqu** [comment]
Hi, sorry for closing this issue without try your fix. After tried it I found that `hyper::common::server::Exec` is private, so I can't call `http.with_executor(Exec::executor(...))` to use a tokio pool as the executor. However I can call a deprecated function `http.executor(any_my_executor)` to associate my executor to the server. Could you show me the best solution?

**Comment by LucioFranco** [comment]
@hicqu this is a good question...I'm not totally sure but this seems more appropriate to make an issue in the hyper repo?

That said, you might be able to satisfy this bound to get it to work? https://github.com/hyperium/hyper/blob/master/src/common/exec.rs#L116

**Comment by LucioFranco** [comment]
@hicqu can this be closed or are you still seeing issues?

**Comment by hicqu** [comment]
It can be closed. Thank you!
