### ISSUE TITLE
Use a single hyper connection as service

### ISSUE THREAD

**Issue by steffengy** [tower-rs/tower-hyper#51]
If I manually construct a connection like
```rust
tower_hyper::client::Builder::new()
                            .http2_only(true)
                            .handshake(sock)
                            .and_then(|(sender, conn)| {
                                    ... spawn conn...
                                    let conn = Connection::new(sender); // private not possible
                                    conn.call(....)
```
there's no way to convert that (sender) into `tower_hyper::Connection`,
since the method is `pub (super)`. Is that intended?

**Comment by LucioFranco** [comment]
@steffengy yes this is intended because the goal is to use `Connect` and `MakeService` to build the connection. Is there a reason you can't use `Connect`?

**Comment by steffengy** [comment]
Well from looking at it, it looks like quit a bit of work for a single connection.

- implement `HttpMakeConnection` for a wrapper that initially returns my single hyper Connection
- implement `HttpConnection` (as required by Connect::new) for a wrapper around a hyper `Connection`
  I also don't quite get why I get around this step, by taking the shortcut of tower_hyper::Connection::new.

Does that sound about right?

**Comment by LucioFranco** [comment]
So you shouldn't have to implement `HttpMakeConnection`, it is just a trait alias for a MakeConnection that returns a `HttpConnection`. `HttpConnection` also has all default impls so its just a fact of `impl HttpConnection for MyStream`. The goal of tower-hyper is really to not have you do the spawning of the background task. I actually didn't even realize you could start the handshake from the `Builder`...I probably should have looked haha.

Hopefully, we will be providing some basic `HttpMakeConnection` impls down the line which is why it may be a lot of work right now.

Maybe if you told me what you're trying to achieve here I could point you in the right direction?

**Comment by steffengy** [comment]
Sure, thanks already for taking the time!
I have a single-reliable UDS (unix domain socket) connection (but it could really be any other transport that implements AsyncRead + AsyncWrite nothing special) and want to do GRPC over it.

So how would I best get a `tower_hyper::Connection` (or anything that implements Service<Request>) from that, so I can send http requests to it?

**Comment by LucioFranco** [comment]
I would go the route of implementing HttpConnection(making sure that the version returns HTTP_2), implement a MakeConnection service that returns the UDS socket that has HttpConnection implemented. Then use `Connect` and `MakeService`.

Here is an example of what you might need to do https://github.com/tower-rs/tower-grpc/blob/master/tower-grpc-interop/src/client.rs#L784

**Comment by steffengy** [comment]
Thanks, seems to work fine.
